apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app
  namespace: nextjs
spec:
  template:
    spec:
      containers:
        - name: nextjs-counter
          resources:
            requests:
              cpu: 1
            limits:
              cpu: 1
